### PR TITLE
seperate task manager + workflow manager

### PR DESCRIPTION
**Pull request by jackschofield23**
### Description

Seperates workflow manager and task manager

### Status
**Work in progress**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] All tests passed locally.
- [ ] [Documentation comments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments) included/updated.

### CODE REVIEW

**Review by mocsharp — APPROVED** [review]
LGTM! 
Was wondering if you would like to rename Task Manager core to Task Executor and call the exe the Task Manager, similar to Workflow Manager & Workflow Executor.

**Comment by jackschofield23** [comment]
@mocsharp I think that may be best for a refactor, as on the workflow side, we have workflowManager as the top level project, and a separate project called workflow executer with the workflow specific logic, we could copy this in the task manager.

**Comment by dbericat** [comment]
Is this separation meaning that they will end up being potentially 2 different containers or services (Helm charts)? 

@nakfour ^^

**Comment by mocsharp** [comment]
> Is this separation meaning that they will end up being potentially 2 different containers or services (Helm charts)?
> 
> @nakfour ^^

Correct, 2 container images/services/helm charts.

**Pull request merged**
