### PR TITLE
Use latest image in Gateway helm values

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
### Description

Use the latest image from
https://github.com/Project-MONAI/monai-deploy-informatics-gateway/pkgs/container/monai-deploy-informatics-gateway/62967058?tag=latest instead of the one from answerdigital, which can not be publicly pulled.

I did not find any "develop-latest" tag, so I used the "latest" tag... however in https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/662/commits and in https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/661 I proposed to use the "develop-latest". You may want to consider to request the monai-deploy-informatics-gateway developers to have such a tag.

See discussion https://github.com/Project-MONAI/monai-deploy-workflow-manager/discussions/658

thanks

### Status
Ready

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [X] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] All tests passed locally.
- [ ] [Documentation comments](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/) included/updated.
- [ ] [User guide updated](../docs).
- [ ] I have updated the [changelog](../docs/changelog.md)

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
I got this error when using this image:

```
jordi@linux-9y1l:~/work/monai-deploy-workflow-manager/deploy/helm (jordi_develop>)$ kubectl logs monai-gateway-9879b8c58-vrqpb
2023-01-30 11:06:23.3960|0|INFO|Monai.Deploy.InformaticsGateway.Program||Initializing MONAI Deploy Informatics Gateway v0.4.0-alpha.105+Branch.develop.Sha.2831d3c5484a20972a24cddf616969c21e8aba1f 
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Monai.Deploy.InformaticsGateway.Database.EntityFramework.EfDatabaseMigrationManager.Migrate(IHost host) in /app/src/Database/EntityFramework/EfDatabaseMigrationManager.cs:line 35
   at Monai.Deploy.InformaticsGateway.Database.DatabaseMigrationManager.MigrateDatabase(IHost host) in /app/src/Database/DatabaseMigrationManager.cs:line 29
   at Monai.Deploy.InformaticsGateway.Program.Main(String[] args) in /app/src/InformaticsGateway/Program.cs:line 68
```

Thus, I am converting this PR to Draft...

**Comment by dbericat** [comment]
@woodheadio @neildsouth can you please help with this? I know we are working on v2 of the Helm charts.

**Comment by jordimassaguerpla** [comment]
> I got this error when using this image:
> 
> ```
> jordi@linux-9y1l:~/work/monai-deploy-workflow-manager/deploy/helm (jordi_develop>)$ kubectl logs monai-gateway-9879b8c58-vrqpb
> 2023-01-30 11:06:23.3960|0|INFO|Monai.Deploy.InformaticsGateway.Program||Initializing MONAI Deploy Informatics Gateway v0.4.0-alpha.105+Branch.develop.Sha.2831d3c5484a20972a24cddf616969c21e8aba1f 
> Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
>    at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
>    at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
>    at Microsoft.Data.Sqlite.SqliteConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
>    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
>    at Monai.Deploy.InformaticsGateway.Database.EntityFramework.EfDatabaseMigrationManager.Migrate(IHost host) in /app/src/Database/EntityFramework/EfDatabaseMigrationManager.cs:line 35
>    at Monai.Deploy.InformaticsGateway.Database.DatabaseMigrationManager.MigrateDatabase(IHost host) in /app/src/Database/DatabaseMigrationManager.cs:line 29
>    at Monai.Deploy.InformaticsGateway.Program.Main(String[] args) in /app/src/InformaticsGateway/Program.cs:line 68
> ```
> 
> Thus, I am converting this PR to Draft...

I see the image does not have the /database directory and I see that inside /opt/monai/ig/appsettings.json 

has this setting for the sqlite:

```
  "ConnectionStrings": {
    "Type": "Sqlite",
    "InformaticsGatewayDatabase": "Data Source=/database/mig.db"
  },
```

How could we change this settings?

**Comment by jordimassaguerpla** [comment]
> /database/mig.db

:thinking: I also need to change the rabitmq settings ...

I was thinking on using ConfigMaps but I am not sure if there is a simpler way... is there?

thanks in advance for this awesome project!

**Comment by dbericat** [comment]
I would hold on for a bit. Most of the values for v1 of the Helm charts are internal to how Answer Digital is building a platform (AIDE) based on MONAI Deploy. 

v2 is when they will make them independent of their environment and generic so others can use OOTB.

**Review by neildsouth — APPROVED** [review]

**Comment by jordimassaguerpla** [comment]
This has been "superseded" by https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/666 .

**Pull request closed without merging**
